# Generated by Django 3.2.9 on 2021-12-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingList', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='user',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
    ]
